// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using susalem.EasyDemo.Repository;

#nullable disable

namespace susalem.EasyDemo.Migrations
{
    [DbContext(typeof(JccRepository))]
    [Migration("20260101033529_AddAutoIncrementToLogId")]
    partial class AddAutoIncrementToLogId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("susalem.EasyDemo.Entities.CabinetInfoModel", b =>
                {
                    b.Property<int>("CabinetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CabinetId");

                    b.Property<string>("ChamName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ChamName");

                    b.Property<string>("DoorAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DoorAddress");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ExpirationDate");

                    b.Property<string>("GreenLightAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("GreenLightAddress");

                    b.Property<bool>("IsNull")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsNull");

                    b.Property<bool>("IsTemperaturing")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isTemperaturing");

                    b.Property<string>("LockAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LockAddress");

                    b.Property<string>("MachineId")
                        .HasColumnType("TEXT")
                        .HasColumnName("MachineId");

                    b.Property<string>("PNCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("PNCode");

                    b.Property<string>("RedLightAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RedLightAddress");

                    b.Property<DateTime?>("TemperatureEndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("TemperatureEndTime");

                    b.Property<DateTime?>("TemperatureStartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("TemperatureStartTime");

                    b.HasKey("CabinetId");

                    b.ToTable("CabinetInfo");
                });

            modelBuilder.Entity("susalem.EasyDemo.Entities.ChemicalParaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CabinetId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CabinetId");

                    b.Property<double>("ExpirationDate")
                        .HasColumnType("REAL")
                        .HasColumnName("ExpirationDate");

                    b.Property<bool>("IsUse")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsUse");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MachineId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("PNCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PNCode");

                    b.Property<double>("ReheatingTime")
                        .HasColumnType("REAL")
                        .HasColumnName("ReheatingTime");

                    b.Property<string>("SerialNum")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SerialNum");

                    b.HasKey("Id");

                    b.ToTable("ChemicalParas");
                });

            modelBuilder.Entity("susalem.EasyDemo.Entities.HistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CabinetId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CabinetId");

                    b.Property<string>("MachineId")
                        .HasColumnType("TEXT")
                        .HasColumnName("MachineId");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("Message");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<DateTime>("OpenCabinetTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("OpenCabinetTime");

                    b.Property<string>("Operater")
                        .HasColumnType("TEXT")
                        .HasColumnName("Operater");

                    b.Property<string>("PNCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("PNCode");

                    b.Property<string>("SerialNum")
                        .HasColumnType("TEXT")
                        .HasColumnName("SerialNum");

                    b.HasKey("Id");

                    b.ToTable("Historys");
                });

            modelBuilder.Entity("susalem.EasyDemo.Entities.RoleModel", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role_name");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.HasKey("RoleId");

                    b.ToTable("hc_roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Level = 1,
                            RoleName = "Admin",
                            State = 0
                        },
                        new
                        {
                            RoleId = 2,
                            Level = 2,
                            RoleName = "User",
                            State = 0
                        });
                });

            modelBuilder.Entity("susalem.EasyDemo.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<string>("CardId")
                        .HasColumnType("TEXT")
                        .HasColumnName("card_id");

                    b.Property<string>("FingerprintId")
                        .HasColumnType("TEXT")
                        .HasColumnName("fingerprint_id");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("RealName")
                        .HasColumnType("TEXT")
                        .HasColumnName("real_name");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<string>("UserIcon")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_icon");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.ToTable("hc_users");
                });
#pragma warning restore 612, 618
        }
    }
}
